const actionType = {
  LOGIN: "LOGIN",
  REGISTER_SUCCES: "REGISTER_SUCCES",
  REGISTER_FAILED: "REGISTER_FAILED",
  LOGIN_SUCCES: "LOGIN_SUCCES",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
};
export default actionType;
