const actionType = {
  LOGIN: "LOGIN",
  REGISTER_SUCCES: "REGISTER_SUCCES",
  REGISTER_FAILED: "REGISTER_FAILED",
  LOGIN_SUCCES: "LOGIN_SUCCES",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_POSTS_LIMIT_ADMIN: "GET_POSTS_LIMIT_ADMIN",
  EDIT_DATA: "EDIT_DATA",
  GET_ACREAGE: "GET_ACREAGE",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICE: "GET_PRICE",
  GET_NEW_POST: "GET_NEW_POST",
  GET_PROVINCES: "GET_PROVINCES",
  RESET_MSG_SUCCESS: "RESET_MSG_SUCCESS",
  RESET_DATA_EDIT: "RESET_DATA_EDIT",

  //USERS
  GET_CURRENT: "GET_CURRENT",
};
export default actionType;
